### ISSUE TITLE
Type 'Socket' cannot be converted to type 'TermWritableStream'.

### ISSUE THREAD

**Issue by paulirish** [paulirish/pwmetrics#101]
```
lib/index.ts(217,20): error TS2352: Type 'Socket' cannot be converted to type 'TermWritableStream'.
  Property 'columns' is missing in type 'Socket'.
```

This manifests in typescript 2.2.2 but wasn't a problem in 2.0.2 (which is what our package.json includes).

yarn vs npm lol

as our types.ts mentions, the upstream issue appears to be https://github.com/DefinitelyTyped/DefinitelyTyped/issues/13508

**Comment by pedro93** [comment]
In the upstream issue there is a code snippet that will fix the issue. We should create a PR on the upstream repo and fix this. I can do it but only after I'm back from vacation.

**Comment by mathiasbynens** [comment]
Sounds like in the mean time, it would make sense to add installation instructions to the README that explicitly use `yarn` instead of `npm`. 👓

**Comment by paulirish** [comment]
@mathiasbynens good call. fixed readme in 1f6ed05

**Comment by denar90** [comment]
@pedro93 @paulirish we already have some fix for this issue https://github.com/paulirish/pwmetrics/blob/master/types/types.ts#L126 so I dunno why it happens. Will investigate though...

**Comment by pedro93** [comment]
I've just confirmed that yarn installation now works on a windows 10 machine. I think we can close this issue @denar90, the installation process seems good 👍 

![pwmetrics](https://cloud.githubusercontent.com/assets/3718654/25557626/3100740c-2cca-11e7-9ada-14ac795b98fc.png)

**Comment by denar90** [comment]
Can confirm the same for `npm i`
