### ISSUE TITLE
Required OptimizedImages gatherer encountered an error

### ISSUE THREAD

**Issue by paulirish** [paulirish/pwmetrics#104]
using latest version

❯ pwmetrics https://bloomberg.com
Launching Chrome
  ✘ Error: Unable to complete run 1 of 1 due to Audit error: Required OptimizedImages gatherer encountered an error: not opened Audit key: uses-optimized-images.

@benschwarz mentioned bloomberg is a tricky page and it always errors. though this error is diff than what he was seeing:

>  ✘ Error: Sorry, Visually Complete 85% metric is unavailable.
> ✘ Error: Sorry, First Contentful Paint metric is unavailable.

anyway.. looks like grabbing the Lighthouse perf config might not be what we want for pwmetrics and we could afford to skip the optimizedimages bit. :)

**Comment by benschwarz** [comment]
I continually see the same for `pwmetrics https://mobile.twitter.com/benschwarz` too:

<details>
<summary>Output</summary>

<pre>
Launching Chrome
  ✘ Error: Sorry, Visually Complete 85% metric is unavailable.
  ✘ Error: Sorry, First Contentful Paint metric is unavailable.

                       |
First Contentful Paint | NaN
                       |
First Meaningful Paint | -1
                       |
Perceptual Speed Index |                                                                                             3,458
                       |
   Time to Interactive | -1
                       ---------------------------------------------------------------------------------------------
                        0                             Time (ms) since navigation start                              3458

</pre>

</details>

**Comment by denar90** [comment]
Hmm, strange, I even can't reach you guys. 
```
> pwmetrics https://bloomberg.com
Launching Chrome
  ✘ Error: Unable to complete run 1 of 1 due to Unable to load the page: .
```

**Comment by denar90** [comment]
Oh nice, bloomberg in Europe redirects to `https://www.bloomberg.com/europe` that's why I get this error. But it's really interesting case which should be handled on LH side and not be throwing error, I think. @paulirish thoughts?

btw, `pwmetrics https://www.bloomberg.com/europe` passed fine for me. FCP - 5,6 sec, TTI - 7,3 sec.

**Comment by benschwarz** [comment]
@denar90 Yup; This is definitely a lighthouse issue—I just discovered it via pwmetrics (while trying to figure out some LH issues I'm having in Calibre). 

@paulirish, Should we close up this issue and ref it on the LH issue tracker?

**Comment by paulirish** [comment]
Yup! Upstream that shii

**Comment by pedro93** [comment]
@paulirish as this is an upstream can I close this issue?

**Comment by paulirish** [comment]
Yup!

**Comment by benschwarz** [comment]
👍 Thanks for copying the issue over @pedro93, I was in the midst of travel and didn't have time to take care of it myself. 🍍
