### ISSUE TITLE
pwmetrics section in package.json ignored

### ISSUE THREAD

**Issue by jooj123** [paulirish/pwmetrics#106]
Running with script command `pwmetrics --config` according to docs will use `pwmetrics` config in `package.json` - so a section such as: 

```
"pwmetrics": {
    "url": "http://www.blah.com",
    "flags": {
      "runs": "2",
      "expectations": true
    },
    "expectations": {
      "ttfcp": {
        "warn": ">=1500",
        "error": ">=2000"
      }
    }
  },
```

Is getting ignored and dumping error message "✘ Error: No url entered.."

Having a seperate js config file like `pwmetrics --config=pwmetrics-config.js` works fine on the other hand

**Comment by craig-mulligan** [comment]
I'm hitting the same thing ☝️

**Comment by pedro93** [comment]
Hello, thanks for filling this issue. 
Could you post the package.json you are using? If possible also the project structure and node version.

**Comment by pedro93** [comment]
A minimal viable example showcasing this would be great to find and fix the bug quickly :)

**Comment by jooj123** [comment]
@pedro93 node `v6.9.1`

I had to strip out some proprietary tools (filled with `xyz`), but you will get the idea from this sample:

```
{
  "name": "xyz",
  "version": "0.0.1",
  "generatorVersion": "1.4.7",
  "description": "xyz",
  "main": "index.js",
  "private": true,
  "scripts": {
    "start": "npm run watch",
    "version": "version-changelog CHANGELOG.md && changelog-verify CHANGELOG.md && git add CHANGELOG.md",
    "watch": "nodemon -w src -x node -r dotenv/config -r babel-core/register src/app.js",
    "watch:docker-compose": "npm run watch -- -L",
    "test:watch": "nodemon -w src -w test -x 'npm test'",
    "test": "mocha -r babel-core/register --opts \"test/unit/mocha.opts\" && npm run lint",
    "test:e2e": "fe-e2e-tests --config test/e2e/nightwatch.conf.js",
    "test:e2e-browserstack": "fe-e2e-tests --config test/e2e/nightwatch.conf.js --browserstack",
    "test:perf": "pwmetrics --config",
    "lint": "eslint src",
    "lint:fix": "eslint src --fix",
    "build": "babel -d lib src -D",
    "flow": "flow",
    "flow:stop": "flow stop",
    "flow:coverage": "flow coverage src/*.js --color"
  },
  "repository": {
    "type": "git",
    "url": "xyz"
  },
  "keywords": [
    "node",
    "react"
  ],
  "author": "Martin Jujou &lt;martin.jujou@domain.com.au&gt;",
  "license": "ISC",
  "bugs": {
    "url": "xyz"
  },
  "homepage": "xyz",
  "dependencies": {
    "xyz": "^3.0.1"
  },
  "devDependencies": {
    "xyz": "^2.2.3"
  },
  "pwmetrics": {
    "url": "http://xyz.com",
    "flags": {
      "runs": "2",
      "expectations": true
    },
    "expectations": {
      "ttfcp": {
        "warn": ">=1500",
        "error": ">=2000"
      },
      "ttfmp": {
        "warn": ">=2000",
        "error": ">=3000"
      },
      "fv": {
        "warn": ">=2000",
        "error": ">=3000"
      },
      "psi": {
        "warn": ">=2000",
        "error": ">=3000"
      },
      "vc85": {
        "warn": ">=2000",
        "error": ">=3000"
      },
      "vs100": {
        "warn": ">=2000",
        "error": ">=3000"
      },
      "tti": {
        "warn": ">=2000",
        "error": ">=3000"
      }
    }
  },
  "eslintConfig": {
    "extends": "xyz",
    "globals": {
      "fetch": false
    }
  },
  "remarkConfig": {
    "presets": "xyz"
  }
}
```

**Comment by craig-mulligan** [comment]
I think this is actually a docs issue. Because running `pwmetrics --config=package.json` works. But the [README](https://github.com/paulirish/pwmetrics#defining-config) insinuates that `pwmetrics --config` would work the same. 

Is it expected to?

**Comment by jooj123** [comment]
@craig-mulligan probably should default to `package.json` for convenience i guess

**Comment by pedro93** [comment]
It should @craig-mulligan due to the default parameter here: https://github.com/paulirish/pwmetrics/blob/master/lib/utils/fs.ts#L6

@jooj123 are you running pwmetrics through npm script right now? Could you try and install globally and executing the same snippet from the terminal in the root dir of your project? 
In your project's root directory:
$ npm install -g pwmetrics
$ pwmetrics --config

**Comment by jooj123** [comment]
I think the issue is this if statement: https://github.com/paulirish/pwmetrics/blob/master/bin/cli.js#L70

Changing to something like:
`config = argv.config ? getConfigFromFile(argv.config) : getConfigFromFile();` works

Im happy to throw up the PR if you can verify thats ok?

**Comment by pedro93** [comment]
I'm not near my laptop to confirm... But @denar90 or @paulirish can validate that very quickly :)

**Comment by pedro93** [comment]
My rough solution would be: 

```js
if(argv.config) config = getConfigFromFile(argv.config !== '' ? argv.config : undefined);
```

The if statement is needed because the config flag may or may not be called. I don't like the code as is though.

If adding 'undefined' as the default value to the the yargs 'config' definition sets the value then this problem can be solved more cleanly. 
E.g: https://github.com/paulirish/pwmetrics/blob/master/bin/cli.js#L47

**Comment by jooj123** [comment]
Yeah sorry i just meant my line temporarily fixed it - its not an ideal fix

I can throw up a PR tomorrow for a clean fix - late here in oz :)

**Comment by denar90** [comment]
Guys, what if instead we set a default value equal to `package.json` in `config` option?
We can achieve a lot of simplifications.
