### ISSUE TITLE
Getting a "TypeError: Cannot read property 'length' of undefined" in pwmetrics 2.0.0

### ISSUE THREAD

**Issue by rpkoller** [paulirish/pwmetrics#108]
Hi I've updated to pwmetrics 2.0.0  few minutes ago. wanted to test things afterwards but ran straight into the following error: 

```
$> pwmetrics https://bloomberg.com
/Users/myuser/.npm_global/lib/node_modules/pwmetrics/node_modules/lighthouse/lighthouse-core/lib/log.js:111
    const maxLength = columns - data.method.length - prefix.length - loggingBufferColumns;
                                           ^

TypeError: Cannot read property 'length' of undefined
    at Function.formatProtocol (/Users/myuser/.npm_global/lib/node_modules/pwmetrics/node_modules/lighthouse/lighthouse-core/lib/log.js:111:44)
    at CriConnection.handleRawMessage (/Users/myuser/.npm_global/lib/node_modules/pwmetrics/node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:111:9)
    at WebSocket.ws.on.data (/Users/myuser/.npm_global/lib/node_modules/pwmetrics/node_modules/lighthouse/lighthouse-core/gather/connections/cri.js:78:37)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:194:7)
    at Receiver.ontext (/Users/myuser/.npm_global/lib/node_modules/pwmetrics/node_modules/ws/lib/WebSocket.js:841:10)
    at /Users/myuser/.npm_global/lib/node_modules/pwmetrics/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/Users/myuser/.npm_global/lib/node_modules/pwmetrics/node_modules/ws/lib/Receiver.js:371:5)
    at /Users/myuser/.npm_global/lib/node_modules/pwmetrics/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/Users/myuser/.npm_global/lib/node_modules/pwmetrics/node_modules/ws/lib/Receiver.js:347:3)
```

I've noticed afterwards that the recommendation changed from using npm for install to yarn. I've installed version 2.0.0 with npm. but thought it wouldn't make a difference in with which app you install a module. So is it recommended to uninstall pwmetrics and reinstall with yarn? i am running npm 4.2.0 and node 7.9.0 on osx 10.11.6 and Canary Version 60.0.3076.0. Cheers r.

**Comment by pedro93** [comment]
Yes, please reinstall via yarn. See https://github.com/paulirish/pwmetrics/issues/101 and linked issue links for more information.

**Comment by rpkoller** [comment]
@pedro93 read this thread. but it puzzles me cuz so far i thought yarn would use the same node_module folder like npm. but it doesnt as i see now. think i have to read up more on that. and the error is the same but now for the yarn folder:

```
$> pwmetrics https://bloomberg.com
Launching Chrome
/Users/myuser/.config/yarn/global/node_modules/lighthouse/lighthouse-core/lib/log.js:111
    const maxLength = columns - data.method.length - prefix.length - loggingBufferColumns;
                                           ^

TypeError: Cannot read property 'length' of undefined
    at Function.formatProtocol (/Users/myuser/.config/yarn/global/node_modules/lighthouse/lighthouse-core/lib/log.js:111:44)
    at CriConnection.handleRawMessage (/Users/myuser/.config/yarn/global/node_modules/lighthouse/lighthouse-core/gather/connections/connection.js:111:9)
    at WebSocket.ws.on.data (/Users/myuser/.config/yarn/global/node_modules/lighthouse/lighthouse-core/gather/connections/cri.js:78:37)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:194:7)
    at Receiver.ontext (/Users/myuser/.config/yarn/global/node_modules/ws/lib/WebSocket.js:841:10)
    at /Users/myuser/.config/yarn/global/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/Users/myuser/.config/yarn/global/node_modules/ws/lib/Receiver.js:371:5)
    at /Users/myuser/.config/yarn/global/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/Users/myuser/.config/yarn/global/node_modules/ws/lib/Receiver.js:347:3)
```
installed with `yarn global add pwmetrics`

**Comment by pedro93** [comment]
@rpkoller thank you, I'm stomped :/ @paulirish could you have a look at this? The stack trace is relative to lighthouse

**Comment by pedro93** [comment]
@rpkoller could you check what version of lighthouse you have in yarn/global? Until lighthouse releases a new version (there are a bunch of fixes we need for v2) we are using a commit specific version that @paulirish provided

**Comment by rpkoller** [comment]
`~/.config/yarn/global/node_modules/lighthouse` says i am running version 1.6.0

**Comment by pedro93** [comment]
@rpkoller can you try and delete all entries in ``` ~/.config/yarn/global/node_modules/``` and run 
```$ yarn remove global pwmetrics && yarn add global pwmetrics``` to force https://github.com/paulirish/pwmetrics/pull/110 to be included in the code?

**Comment by denar90** [comment]
@rpkoller can you reinstall? I've published v2.0.1 with fixes. Should be working for you.

**Comment by rpkoller** [comment]
@denar90  @pedro93 honestly speaking I would and want but somehow Yarn and me had a rough start. ;) Basically I am rather confused right now. I had yarn installed with brew a while ago. Never used it so far. Then I've installed `pwmetrics` with `yarn add global pwmetrics` as it was recommended for `pwmetrics 2.0.0` and I've uninstalled the `npm` `pwmetrics` version beforehand. When I check `~/.config/yarn/global/node_modules/`there are a bucketload of modules there aside `pwmetrics` which is the only dependency listed in `~/.config/yarn/global/package.json`. When I am in my home directory and try to remove the old pwmetrics version I get: 

```
$> yarn remove global pwmetrics
yarn remove v0.23.3
error No lockfile in this directory. Run `yarn install` to generate one.
```

Afterwards the `pwmetrics` folder is still present. So basically I am unable to remove `pwmetrics` folder inside the `yarn` `global` folder. And i am unsure if I am allowed to just remove the whole `node_modules` folder there. Cuz it seems it might contain modules for yarn itself as well. Always expected that `yarn` and `npm` share the same folder for the `npm_modules`.  Guess I need to read up a bit more the yarn docs beforehand I suppose. 

p.s. I've noticed one thing right before I wanted to submit the comment. The `yarn` `npm_modules` contain also a `Lighthouse` folder. But I haven't removed the npm version yet. So that might be also a possible issue?

**Comment by rpkoller** [comment]
uhhhh bummer due to the fact that i never used Yarn so far actually I forgot about to add `~/.config/yarn/global/node_modules/.bin` for the global bin folder to the path in my bash_profile. :/ Dumb oversight. With that in place it is working now flawlessly already with 2.0.0 . Found while going through the yarn issues on github. Sorry for the trouble. :( But never the less one question still persists on my end which would help understanding yarn quite a bit. does the global ``~/.config/yarn/global/node_modules/`folder contain each and every module yarn needs and uses and not only those installed by the user globally afterwards like with npm? And how do you handle things. are you using two global module bases alongside? npm AND yarn? or do you stick to one of them?

**Comment by pedro93** [comment]
Glad to hear your issue is solved. We provide both npm and yarn installations but we advise using yarn as suggested in the repo readme. There was recently an issue with npm and us using a commit-specific version of lighthouse but that should be solved as soon as a new version of lighthouse is released (scheduled for the Google I/O). I will close this issue. Please comment if you feel anything is relevant is still not done for the original problem.
