### ISSUE TITLE
pwmetrics section in package.json ignored

### ISSUE THREAD

**Issue by jooj123** [paulirish/pwmetrics#117]
This issue is back:
https://github.com/paulirish/pwmetrics/issues/106

It was originally fixed here:
https://github.com/paulirish/pwmetrics/pull/107

But looks like this PR breaks it (as it no longer defaults to `package.json` now):
https://github.com/paulirish/pwmetrics/pull/112

**Comment by pedro93** [comment]
__Edit__
I just created a project to try to reproduce this and have been unable to. How are you hitting this error? 
I simply created a node project with ```npm init && npm install --save-dev pwmetrics```, added the pwmetrics option in the package.json:
```js
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "pwmetrics --config"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "pwmetrics": "^2.0.2"
  },
  "pwmetrics" : {
    "url": "http://www.blah.com",
    "flags": {
      "runs": "2",
      "expectations": true
    },
    "expectations": {
      "ttfcp": {
        "warn": ">=1500",
        "error": ">=2000"
      }
    }
  }
}
```

And got the following:

![pwmetrics output](https://cloud.githubusercontent.com/assets/3718654/26036123/f73f17b6-38cf-11e7-994f-68055c34176d.png)

Directly from the console also works:
![pwmetrics console](https://cloud.githubusercontent.com/assets/3718654/26036151/7cd270a8-38d0-11e7-8ac1-d5e81ac7f18f.png)

**Comment by denar90** [comment]
@jooj123 do you use latest version?

**Comment by jooj123** [comment]
Yep i have the latest

The difference is that im running just `pwmetrics` without the `--config` - which makes sense because the docs mention 
"# --config        Provide configuration (defaults to `package.json`). See _Defining config_ below."

**Comment by pedro93** [comment]
Ok, that is an error in the readme. What was meant was: if you want to use a config file, use the config flag. If no path is given, defaults to package.json of the current directory.

Will making the readme clearer be enough for you @jooj123?

**Comment by denar90** [comment]
fixed by https://github.com/paulirish/pwmetrics/commit/dae68c71c5964ee30b91695f36ad092a3c467534
