### ISSUE TITLE
Upgrade to latest lighthouse

### ISSUE THREAD

**Issue by paulirish** [paulirish/pwmetrics#119]
There's a [alpha](https://github.com/GoogleChrome/lighthouse/pull/2262) release of the 2.0 that we can give a go over here:

`lighthouse@canary` will work, but you could also use the specific release.. currently `lighthouse@2.0.0-alpha.6`

We'll probably ship the real 2.0 on friday, but if you two want to test things out here, we can verify we don't have any Lighthouse-side bugs. :)

Also.. brand new metrics!

**Comment by denar90** [comment]
I also have been thinking about that but faced some concerns.
1. TTI is no longer what we need. So if we bump to LH alfa version, do we
have to make v3 release? What to do when we bump to real LH 2? v4?
2. LH has updated chrome launcher, so I'd like to update our code to this
stuff.

**Comment by pedro93** [comment]
Doesn't the new lighthouse version have a new version of TTI, which is supposed to be more stable?
Maybe we can also make a V3-alpha version to match lighthouse and release the stable version along-side lighthouse.

There are multiple areas I would also like to change, to fix our linting warnings for instance. Perhaps re-propose the desiredMetric functionality, it was recently requested.

If we do end up changing stuff (other than the lighthouse version) more likely than not it will not be ready by Friday.

**Comment by denar90** [comment]
Yeap, new TTI version is cool. I'm more than 👍 to bring it here asap.


>There are multiple areas I would also like to change, to fix our linting warnings for instance. Perhaps re-propose the desiredMetric functionality, it was recently requested.

It can be as part of v3.x so no rush here.

**Comment by paulirish** [comment]
yes TTI is gonna. it basically splits into TTFI and TTCI.

**Comment by denar90** [comment]
Fixed by #120
