### ISSUE TITLE
pwmetrics returns `exit 0` when one of the expectations is not correct

### ISSUE THREAD

**Issue by willmendesneto** [paulirish/pwmetrics#127]
### About this issue

I'm using pwmetrics, but I'm receiving a false positive when one of the expectations are passing. I couldn't find a way to make it pass only when all expectations are correct in the docs.

### Config / CLI options

```javascript
module.exports = {
  url: 'http://localhost:3000',
  flags: {
    runs: '1',
    submit: false,
    upload: false,
    view: false,
    expectations: true,
    disableCpuThrottling: false,
    chromeFlags: [
      '--incognito',
      '--aggressive-cache-discard',
      '--headless',
    ],
  },
  expectations: {
    ttfcp: {
      warn: '>=1500',
      error: '>=3000',
    },
    ttfmp: {
      warn: '>=2000',
      error: '>=4000',
    },
    fv: {
      warn: '>=1500',
      error: '>=4000',
    },
    psi: {
      warn: '>=1500',
      error: '>=3000',
    },
    vc85: {
      warn: '>=1500',
      error: '>=3000',
    },
    vs100: {
      warn: '>=1500',
      error: '>=4000',
    },
    tti: {
      warn: '>=1500',
      error: '>=4000',
    },
  },
};
```

### Steps to reproduce.

I tried to make it run using 

```shell
# run-pwmetrics.sh
#!/usr/bin/env bash
set -e
set -o pipefail

pwmetrics http://localhost:3000/landing --config=./pwmetrics-config.js 2> /dev/null
OUT=$?

echo "OUT: ${OUT}"
if [ $OUT -eq 0 ]
then
  echo "Successfully"
else
  echo "Error" >&2
fi
```

```bash
$ ./run-pwmetrics.sh
```

PS:

- I tried run via npm script adding the same command as a npm script and both return the same error.

### Screenshot

![screen shot 2017-07-10 at 3 09 49 pm](https://user-images.githubusercontent.com/1252570/28003554-e13a4cfe-6581-11e7-91fa-76d0738dfa0a.png)

### Environment

1. `pwmetrics` version: 2.0.2
2. Chrome version: Version 59.0.3071.115 (Official Build) (64-bit)
3. OS version: macOS Sierra 10.12.5 
4. NodeJS version: v6.10.0
5. Yarn version: v0.27.5

**Comment by pedro93** [comment]
As of right now the status code of pwmetrics is relative to a successful auditing execution and not the values of that execution. 

If for some reason pwmetrics (actually lighthouse under the hood) was unable to retrieve the page load event for example, it could not compute the metrics which would lead to a crash in the program (see https://github.com/paulirish/pwmetrics/issues/74 for example). 

Perhaps this should be changed when expectations are set. CC @denar90

**Comment by paulirish** [comment]
Agree that the exit code should definitely be non-zero if there was an error within the expectations.

(TBH we should be exiting with 1 here as well: https://github.com/paulirish/pwmetrics/blob/6aea514f185901d7641750fda5d20c52a20a0d5a/lib/expectations.ts#L12 )

**Comment by willmendesneto** [comment]
@paulirish About the `process.exit(1)` that you linked, it's solved in this commit (it's on PR right now). https://github.com/paulirish/pwmetrics/pull/128/commits/5c3a392cf17847ad020e70952da089a197fd45f5#diff-8ad51fb63d3211deee9a805a512386adR12

**Comment by willmendesneto** [comment]
Closing this issue. It was solved in [this commit](https://github.com/paulirish/pwmetrics/commit/c72a0d03c488a89807514930fb49d3111154062b). Thanks everyone.
