### ISSUE TITLE
Local server running feature

### ISSUE THREAD

**Issue by denar90** [paulirish/pwmetrics#13]
Hey guys, it's me again 😃  To use pwmetrics with CI we should run some server and then run metrics passing current url (e.g. localhost:8080/index.html). What do you think about adding possibility to run server for special file using CLI? I propose smth like
`pwmetrics public/index.html --local`

**Comment by paulirish** [comment]
wouldn't that be fairly equivalent to the following?

```sh
cd public; python -m SimpleHTTPServer 8000; pwmetrics http://localhost:8000/index.html;
```

I'm not crazy about adding an optional static server into pwmetrics as many setups require a slightly more complicated server.

**Comment by denar90** [comment]
Fair enough. Closing then)
