### ISSUE TITLE
Feature Request: Add chromePath as an option to test with a specific version of Chrome

### ISSUE THREAD

**Issue by cheneytsai** [paulirish/pwmetrics#130]
It seems like currently pwmetrics launches with the latest version of Chrome, since the underlying chrome-launcher has support for [chromePath](https://github.com/GoogleChrome/lighthouse/blob/master/chrome-launcher/chrome-launcher.ts#L93-L96), should we add the option in pwmetrics?

**Comment by pedro93** [comment]
I don't see any reason why not. Want to make a PR?

**Comment by natedanner** [comment]
PR opened. https://github.com/paulirish/pwmetrics/pull/134
