### ISSUE TITLE
Audit error: trace not at least 5 seconds longer than FMP Audit key: first-interactive

### ISSUE THREAD

**Issue by denar90** [paulirish/pwmetrics#132]
### Config / CLI options
`pwmetrics https://example.com`

### Steps to reproduce.
run `pwmetrics https://example.com`

### Stack trace
```bash
Launching Chrome
  ✘ Error: Unable to complete run 1 of 1 due to Audit error: trace not at least 5 seconds longer than FMP Audit key: first-interactive.
```

### Environment
1. `pwmetrics` version: 3.0.1
2. Chrome version: Version 61.0.3162.0 (Official Build) canary (64-bit)
3. OS version: MacOs Sieera 10.12.4

**Comment by staabm** [comment]
same on 
  pwmetrics 3.1.0
  win10
  Chrome 62.0.3169.0
  node 8.2.1

**Comment by denar90** [comment]
Looks like LH is not providing metrics we needed.
Our logic is dumb, get metrics -> draw chart, if there are no metrics -> throw error.
I'm wanna change it to - get metrics -> draw chart, if there are no metrics -> draw chart but with missed metrics.
I have one problem - time. Really really hope to look at it on a weekend.
Today is #opesourcefriday but not at my company...

**Comment by pedro93** [comment]
@denar90 and @staabm can you reproduce this consistently? I've been trying but pwmetrics works fine for me.

Pwmetrics version: 3.1.0 (from master)
Chrome version: 60.0.3112.78
OS: Ubuntu 16.04 LTS
NodeJS: v8.2.1

**Comment by denar90** [comment]
Yup. Still have this issue consistently...
