### ISSUE TITLE
No domContentLoaded event in trace Audit key: first-interactive.

### ISSUE THREAD

**Issue by epodgaetskiy** [paulirish/pwmetrics#135]
pwmetrics https://gdesport.info

 Error: Unable to complete run 1 of 1 due to Audit error: No domContentLoaded event in trace Audit key: first-interactive.

Can you help me about this error?

**Comment by denar90** [comment]
It's related to https://github.com/paulirish/pwmetrics/issues/132 
Looks like some metrics results are misssed. 
I'll try to debug Lighthouse and get back with results.

**Comment by pedro93** [comment]
@epodgaetskiy What are you system's characteristics? Node, pwmetrics, chrome and OS version?

I managed to run it fine:
![screenshot from 2017-07-29 10-48-36](https://user-images.githubusercontent.com/3718654/28743828-82b01c26-744b-11e7-8575-0902f9418487.png)

**Comment by denar90** [comment]
`node v8.2.1`
`npm 5.3.0`
`chrome - latest canary`
