### ISSUE TITLE
Expose LH runner logic into single file/module/folder

### ISSUE THREAD

**Issue by denar90** [paulirish/pwmetrics#137]
Having it in single file/module/folder might be helpful for others, kinda chrome-launcher...
It will be like proxy
` perf conf => [balck box (running chrome and LH)] => return result `

**Comment by pedro93** [comment]
Can you elaborate on the "perf conf"? Do you mean that the input for pwmetrics will be a performance LH report and we just generate the graph from it?

**Comment by denar90** [comment]
no no. nothing changes for pwmetrics. lighthouse-runner is just a class which can run lighthouse and return a result.
interface params kinda:
```
interface LigthouseRunnerOptions {
  url: string,
  pathtoPerfConfig: string,
  chromeLuncherOptions: ChromeLauncherOptions
}
```

**Comment by denar90** [comment]
I'm not sure we gonna implement it...
