### ISSUE TITLE
chrome asks to translate the page

### ISSUE THREAD

**Issue by staabm** [paulirish/pwmetrics#140]
when issue the `pwmetrics` command, google chrome starts up and the UI blocks because chrome asks whether it should "translate this page". 

no matter whether I allow/deny this dialog chrome closes after 5 seconds and the console output appears. IMO DX wise it would be less confusing when chrome would not ask questions (or at best would start invisible). couldn't pwmetrics use headless chrome?

### Config / CLI options
```
pwmetrics http://example.com/
Launching Chrome
Audit error: trace not at least 5 seconds longer than FMP Audit key: first-interactive
Audit error: Main thread activity continued through the end of the trace recording. Consistently Interactive requires a minimum of 5 seconds of both main thread idle and network idle. Audit key: consistently-interactive

                                         |
Time to Consistently Interactive (vBeta) | -408,653,676
                                         |
               First Interactive (vBeta) | -408,653,676
                                         |
                  Perceptual Speed Index |                                                     762
                                         |
                  First Meaningful Paint |                                                   739
                                         |
                  First Contentful Paint |                                                   739
                                         --------------------------------------------------------------------
                                          0                 Time (ms) since navigation start                  1000
  ✓ Success: Run 1 of 1 finished successfully.
```

### Environment
1. `pwmetrics` version: 3.1.1
2. Chrome version: 62 nightly
3. OS version: win10x64

### Screenshot

![grafik](https://user-images.githubusercontent.com/120441/28766270-228ccb16-75cf-11e7-8bc7-7b731f6e8ff9.png)

**Comment by paulirish** [comment]
A little surprised by this as I believe `--disable-translate` is set on the launched chrome instance.. You can verify this by opening `about:version` in a new tab in that chrome window and checking the flags used.

**Comment by paulirish** [comment]
fwiw  chrome-launcher default flags: https://github.com/GoogleChrome/chrome-launcher/blob/master/flags.ts

**Comment by pmeenan** [comment]
Looking into a similar issue for WebPageTest, it looks like the --disable-translate command-line option was removed at some point.

**Comment by denar90** [comment]
@pmeenan which Lighthouse version do you use?

**Comment by pmeenan** [comment]
I'm seeing it independent of Lighthouse (in WebPageTest which uses the same command-line option).

The disable-translate flag was [removed ~6 months ago](https://codereview.chromium.org/2819813002/) apparently.  

It can be disabled with a machine policy (easy on Linux, royal pain everywhere else) or by writing a Preferences file to the profile with the translate preference disabled.  WebPageTest is using both the policy file and pref as of a couple of minutes ago but there's not a good solution for Android yet that I have found.

**Comment by denar90** [comment]
>The disable-translate flag was removed ~6 months ago apparently.

cc @paulirish

**Comment by pmeenan** [comment]
It looks like it's not a problem on most platforms because the --disable-infobars command-line option (or one of the others I set) disables the new UI so it's only platforms where the old message box is displayed (Linux in my testing).  Writing a pref to the profile directory before launching or using the policy file both successfully disable it.

For WebPageTest [here](https://github.com/WPO-Foundation/wptagent/blob/master/internal/support/chrome/prefs.json) is the pref file that I write to {profile}/Default/Preferences before launching Chrome.

**Comment by staabm** [comment]
I experienced the initially reported problem on windows10x64

**Comment by denar90** [comment]
@pmeenan thank you for these clarifications.
@staabm do you still have this problem, because on macOS it looks fine.

**Comment by staabm** [comment]
I can still reproduce the issue with pwmetrics 3.1.2 and chrome 64.0.3264.0

**Comment by staabm** [comment]
tested with the latest version of chrome and pwmetrics. 

the issue seems fixed.

tested on chrome 65 and pwmetrics 3.1.4
