### ISSUE TITLE
Improve pwmetrics-config

### ISSUE THREAD

**Issue by denar90** [paulirish/pwmetrics#143]
wdyt if we improve config and make it array instead of object? So we could run CI for several urls with different expectations or other flags.

**Comment by pedro93** [comment]
Do you have an example?
How would it be different from calling pwmetrics multiple times with different configs?

**Comment by denar90** [comment]
It will be useful for CI. So instead of running pwmetrics in loop, users will provide us with config and we do work for them.
config example
```
module.exports = [
{
  url: 'http://example.com/',
  expectations: {
    ttfcp: {
      warn: '>=1500',
      error: '>=2000'
    },
    ttfmp: {
      warn: '>=2000',
      error: '>=3000'
    }
  }
},
{
  url: 'http://example.com/awesome-page',
  expectations: {
    ttfcp: {
      warn: '>=1000',
      error: '>=2000'
    },
    ttfmp: {
      warn: '>=1500',
      error: '>=2000'
    }
  }
}];


```

**Comment by pedro93** [comment]
Ok, what about repeat runs?

**Comment by denar90** [comment]
do you see the problem here? we can just wait for all runs are done for the first element of array, then do it for the second etc...

**Comment by pedro93** [comment]
I don't really see the advantage. Perhaps I do not understand the underlying problem. 
In a CI environment I see 2 potential problems:

1.) Having to define multiple configurations files each with different expectations and flags for each different URL you may want to test.

2.) Parallelize as much independent runs as possible. For example, suppose you have a website with 5 different urls you want to test. To get accurate performance readings you want the mean metrics of 10 runs. This means that a single pwmetrics process will have to run 50 times per performance evaluation you may want to do. 

This takes time (assuming a 30 second period per test, that's 1500 seconds or 25m assuming the CI environment has enough slave instances, CPU and ram available to run all tests + performance), I don't think it would be uncommon to try to do on a PR or commit frequency-basis.

The first problem could be addressed by the suggested improvement as a built-in solution. However, I think to do so would be in detriment of making it harder to solve the second problem and for a nice-to-have feature which could just as easily be implemented on top of pwmetrics.

**Comment by denar90** [comment]
Good points, yeah if someone needs several urls to verify then several configs the way.
