### ISSUE TITLE
json option also outputs graphical representation

### ISSUE THREAD

**Issue by staabm** [paulirish/pwmetrics#144]
why does the `--json` flag also output a graphical represenation?
I would expect only the json information, so I can process the data further..

### Config / CLI options
pwmetrics http://example.com --json

### Screenshot
![grafik](https://user-images.githubusercontent.com/120441/31664133-8d2775f4-b344-11e7-930b-628eca4d4056.png)

### Environment
1. `pwmetrics` version: 3.1.2
2. Chrome version: 64 beta
3. OS version: windows10x64

**Comment by denar90** [comment]
should be fixed with 3.1.3 release.

**Comment by denar90** [comment]
* 3.1.4
