### ISSUE TITLE
Comparing measurements between headless and none headless modes for perf metrics

### ISSUE THREAD

**Issue by denar90** [paulirish/pwmetrics#151]
As @paulirish [mentioned](https://github.com/paulirish/pwmetrics/pull/147/files#r160195545) there is no proof to be sure that metrics got from headless and none headless modes the same.

So I've done some experiments, running 15 times in default and 15 in headless mode. [Results](https://docs.google.com/spreadsheets/d/1ReQfNXTK0QY202pAeXVkQFmNPNLOVGzqwPNxCZL-h_0/edit?usp=sharing) are pretty the same:

![image](https://user-images.githubusercontent.com/6231516/35752723-abce7b1c-0865-11e8-8f87-978206522f58.png)

**Comment by pedro93** [comment]
Great ideia, we should this kind of investigation more often! I have some questions about the results though, they don’t make much sense to me in the spreadsheet I only see 21 runs, where’s the rest? Which ones are headless and which aren’t?

**Comment by denar90** [comment]
sorry, I've played a bit with diagrams, now it's restored.
here's better screenshot
![image](https://user-images.githubusercontent.com/6231516/35754110-efab7b82-086a-11e8-83e5-02adf8fdf29d.png)
