### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:9222

### ISSUE THREAD

**Issue by feifeipan** [paulirish/pwmetrics#155]
### Config / CLI options
```
pwmetrics http://www.ctrip.com
```

### Screenshot

![2018-03-01 6 21 20](https://user-images.githubusercontent.com/2155605/36839755-e7ada9e6-1d7d-11e8-89d7-168957036c65.png)

### Environment
1. `pwmetrics` version: 3.1.5
2. Chrome version:64.0.3282.186
3. OS version: macOS 10.13.3 

"npm install -g pwmetrics", then run the command.

I've searched chrome_loader, but still have no idea. May someone help me?

**Comment by formatlos** [comment]
I do have the same issue, someone has already fixed it here https://github.com/paulirish/pwmetrics/pull/154 but it'S not merged and published.

**Comment by feifeipan** [comment]
Thanks a lot. It worked!

**Comment by denar90** [comment]
Sorry, I'll try to publish new version tonight.

**Comment by formatlos** [comment]
@denar90 thanks a lot.  Would it also be possible to upgrade chrome-launcher version as I want to run it on alpine linux and the used one is buggy

**Comment by denar90** [comment]
New version is published, chrome-launcher version also was bumped. Can we close this issue?

**Comment by formatlos** [comment]
looks good for me! thanks a lot.

**Comment by donaldpipowitch** [comment]
I hit the same error by using this:

```
module.exports = {
  flags: {
    chromePath: require('puppeteer').executablePath()
  }
};
```

```
module.exports = {
  flags: {
    chromePath: require('puppeteer').executablePath()
  }
};
```

**Comment by donaldpipowitch** [comment]
> do you have already run http://localhost:8080 and it can be reached?

Yes.

```
$ curl localhost:8080
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
...
```

> can you try remote website instead?

Same error.

```
$ pwmetrics https://www.google.com --config=pwmetrics.config.js
Launching Chrome
{ Error: connect ECONNREFUSED 127.0.0.1:51875
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 51875 }
```

> do you have installed chrome in folder require('puppeteer').executablePath()? 

As far as I can tell, yes. It points to a valid path and the files exist.

> can you try pwmetrics http://localhost:8080 --chrome-path=path-to-chrome?

Same result.

---

Note: I tried this with the Windows Subshell for Linux (WSL).

**Comment by denar90** [comment]
have you tried --no-sandbox flag?

**Comment by donaldpipowitch** [comment]
Sorry, I can't remember and don't work on Windows anymore :/

**Comment by denar90** [comment]
Sorry for the delay.
Closing this one.

**Comment by barreirabruno** [comment]
Hey guys, I get the same issue here =/

**Comment by denar90** [comment]
Hi @barreirabruno, have you tried any of advice?

**Comment by barreirabruno** [comment]
Hey @denar90 it wasn't a Docker error. 
My .env variables were not imported properly. 
Now its working.

**Comment by denar90** [comment]
closing in favor of https://github.com/paulirish/pwmetrics/issues/179
