### ISSUE TITLE
Update LH dep to v3

### ISSUE THREAD

**Issue by denar90** [paulirish/pwmetrics#158]
We should prepare our codebase to LH v3.

1. Take a look at LHR details https://github.com/GoogleChrome/lighthouse/pull/4616
2. Improve code and tests

**Comment by paulirish** [comment]
I'd say hold off for a moment. While I have a few PRs that are about to land, the bigger change will be when we nuke extendedInfo. 

Around that time, we'll ask you guys how you'd prefer to pull in the timing/timestamp values.. as there's a few ways we could do it.

And here's two slightly better links than 4616:

https://github.com/GoogleChrome/lighthouse/issues/4614#issuecomment-368111051
https://github.com/GoogleChrome/lighthouse/issues/4333

**Comment by denar90** [comment]
We can close this one since #178 merged
