### ISSUE TITLE
Question about google sheets / drive integration

### ISSUE THREAD

**Issue by jooj123** [paulirish/pwmetrics#173]
Is there a way to automate the sheets / drive integration through CI without manual intervention?

Seems that at the moment you need to manually enter an oauth code to authorise - not sure if there is a way to automate that part (maybe with puppeteer?)

If there isn't a way to do this currently and you have suggestions on how it could be done - im willing to give it a go in my spare time 👍 

I ideally want to have a history of perf results over time with the sheets / drive integration - so I can pick up on what changes introduced degraded perf and improved perf (and also non tech stakeholders can view the reports easily)

@denar90 @paulirish

**Comment by denar90** [comment]
I see one option here - having different configs with keys...

**Comment by denar90** [comment]
Closing this one...
