### ISSUE TITLE
wunderbar fails with "TypeError: Unexpected options.max: null. Expected number"

### ISSUE THREAD

**Issue by jooj123** [paulirish/pwmetrics#175]
### Steps to reproduce.

~This happens when pwmetrics / lighthouse fails to generate any timings~ (nope, happens even when you have timings with my website).
This happens alot with my website but seems to be fine with other websites (ill keep trying to figure out reproduce steps..)

### Stack trace

```
14:54:33 [tests] TypeError: Unexpected options.max: null. Expected number
14:54:33 [tests]     at normalizeOptions (/workspace/search-results_PR-1874-head-PPB4NMFRURBGLRE3KKGPQTRTPXHLZJSJNIIQ55HIBBQO44HPZKKA/node_modules/@gribnoysup/wunderbar/lib/normalizers.js:47:11)
14:54:33 [tests]     at draw (/workspace/search-results_PR-1874-head-PPB4NMFRURBGLRE3KKGPQTRTPXHLZJSJNIIQ55HIBBQO44HPZKKA/node_modules/@gribnoysup/wunderbar/lib/index.js:62:7)
14:54:33 [tests]     at drawChart (/workspace/search-results_PR-1874-head-PPB4NMFRURBGLRE3KKGPQTRTPXHLZJSJNIIQ55HIBBQO44HPZKKA/node_modules/pwmetrics/lib/chart/chart.js:14:23)
14:54:33 [tests]     at PWMetrics.showChart (/workspace/search-results_PR-1874-head-PPB4NMFRURBGLRE3KKGPQTRTPXHLZJSJNIIQ55HIBBQO44HPZKKA/node_modules/pwmetrics/lib/index.js:232:9)
14:54:33 [tests]     at PWMetrics.displayOutput (/workspace/search-results_PR-1874-head-PPB4NMFRURBGLRE3KKGPQTRTPXHLZJSJNIIQ55HIBBQO44HPZKKA/node_modules/pwmetrics/lib/index.js:216:18)
```

### Environment
1. `pwmetrics` version: 3.2.1
2. Chrome version: 64
3. OS version: node:8.9.4-slim (docker image)

**Comment by jeremyfrank** [comment]
Same result for me running `pwmetrics https://airhorner.com/` in Node 8.11.1 with Lighthouse 2.9.4 and Chrome 65. Oddly, when I run the same command with the `--json` flag, it completes successfully.

**Comment by jooj123** [comment]
Yep i found this as well @jeremyfrank - im not convinced its due to no timings being sent to `wunderbar` (ill change the description) - we are stuck with the plain JSON output in CI for the time being until this is fixed (ideally we should have nice charts in CI)

**Comment by gribnoysup** [comment]
@jeremyfrank @jooj123 running PWMetrics on airhorner always produces result with a missing FCP metric for me. Do you have a reproduction scenario where the timings are NOT missing and the chart drawing fails?

**Comment by gribnoysup** [comment]
I created a PR that should fix the issue when some metrics are not recorded by Lighthouse

As for the case where all the metrics are recorded but chart still fails to print, I still can't reproduce it, sorry 😿

**Comment by jeremyfrank** [comment]
No, I wasn't able to reproduce the same error with the other sites I tested. Strange that I only saw it happen with the airhorner site.
