### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:9222

### ISSUE THREAD

**Issue by earnedmarketing** [paulirish/pwmetrics#179]
### Config / CLI options
Vanilla CLI and node executions

### Steps to reproduce.
1. Launch a clean Ubuntu droplet with Digital Ocean
2. Install latest Node LTS, pwmetrics, chromium
3. Try using the official examples of launching pwmetrics via CLI or Chrome

(you get an unintelligible error which seems to be because your default settings for the CLI and the node execution are missing --no-sandbox flag which seems to have been required for more than half a year - https://github.com/karma-runner/karma-chrome-launcher/issues/158)

### Stack trace
{ Error: connect ECONNREFUSED 127.0.0.1:42565
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 42565 }
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:9222
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

### Environment
1. `pwmetrics` version: 3.2.1
2. Chrome version: Chromium 66.0.3359.181
3. OS version: Ubuntu 16.04

**Comment by 4idlm** [comment]
{ Error: connect ECONNREFUSED 127.0.0.1:9222
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1173:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9222 }

I am facing this issue ,I need help

**Comment by denar90** [comment]
@4idlm do you have the same conditions and platform as @earnedmarketing?

**Comment by denar90** [comment]
should be fixed using `chromeFlags` - https://github.com/GoogleChrome/lighthouse/issues/2462#issuecomment-311213223

Will be added in example in #178

**Comment by denar90** [comment]
Example of CI run https://travis-ci.org/paulirish/pwmetrics/jobs/421316522

**Comment by 4idlm** [comment]
thanks for your help man..i was fixed that issue..
