### ISSUE TITLE
Feature Request: Also capture audit category scores and add them to google sheets

### ISSUE THREAD

**Issue by gsemfield** [paulirish/pwmetrics#180]
The existing metrics are great. Could it be possible to capture of the following audit category score results in addition to the existing captured metrics. Could these new scores also be sent to google sheets in the same way when using the submit option?
"id": "performance"
"id": "pwa"
"id": "accessibility"
"id": "Best-Practices"
"id": "seo"

**Comment by denar90** [comment]
Sorry, by we just relay on metrics not any other LH scores...
