### ISSUE TITLE
Expectation errors should be based on median run values

### ISSUE THREAD

**Issue by tshen8** [paulirish/pwmetrics#181]
When performing multiple runs on a page with expectation set, the entire testing process will fail if _any_ one of the runs exceeds any expectation value.

If the purpose of doing multiple runs is to gather several data points for performance metrics in order to rule out outliers and unrepresentative numbers, I think it makes sense that the pass/fail should be based on the median numbers for the runs (which are displayed at the end anyways).

What do you guys think? I'm happy to make a PR if we're okay with this.

**Comment by denar90** [comment]
should be fixed via #178

**Comment by denar90** [comment]
Hi, @brophdawg11. Hope really soon, but need some polishing. Working on that...

**Comment by denar90** [comment]
closing since #178 merged
