### ISSUE TITLE
Hide console output

### ISSUE THREAD

**Issue by santoshjoseph99** [paulirish/pwmetrics#184]
When using the API, I think it would be good idea not to output anything to the console, since you get that data from the `start` call.
Seems pretty simple, just pass a flag into the `options` object to silence the `console.log`'s.
I can get this done if needed.

output when using API:
<img width="751" alt="screen shot 2018-07-31 at 9 29 40 pm" src="https://user-images.githubusercontent.com/461049/43501135-ea3f2542-9508-11e8-9eb1-dbac8082f377.png">

### Environment
1. `pwmetrics` version:
2. Chrome version:
3. OS version:

**Comment by denar90** [comment]
I think we can use flag her, aka `showLaunchingResults` which might be true by default. wdyt?

**Comment by santoshjoseph99** [comment]
sounds good. I'll submit a PR.

**Comment by denar90** [comment]
fixed via #185
