### ISSUE TITLE
Typo in error logging for gsheets

### ISSUE THREAD

**Issue by AlahmadiQ8** [paulirish/pwmetrics#186]
Please see line https://github.com/paulirish/pwmetrics/blob/master/lib/sheets/gsheets.ts#L54

looks like it should be `logger` instead of `log`

I can create a PR for this (not sure whats the PR process like).

**Comment by denar90** [comment]
Indeed. I'll add this in #178

**Comment by denar90** [comment]
closing since #178 merged
