### ISSUE TITLE
Add ability to upload median values only to sheets?

### ISSUE THREAD

**Issue by timstallmann** [paulirish/pwmetrics#201]
Hi! 

This would seem to be a natural follow-up to #181. I'd love to see a config file value like `sheets.options.reportMedianOnly` which would only upload the median value for each metric across that batch of runs. 

I'd be down to poke in the code and try to work on a PR, if folks feel like that's a worthwhile feature?

**Comment by denar90** [comment]
Hi. Looks like it's also related to #199. I'll be more than happy to have this feature.

PR's are always welcome 😄

**Comment by denar90** [comment]
thx, published with v4.2.0 release
