### ISSUE TITLE
Metrics so different between CLI's

### ISSUE THREAD

**Issue by carlesnunez** [paulirish/pwmetrics#213]
Hello everyone!

This is more a question than a problem. I've been running tests on same page, same environment, same network with pwmetrics, audits and lighthouse-cli and pwmetrics give me values on TTI or FCPUIdle 3-4 s under the values that audits or lighthouse-cli give.

Why is this happening? I've checked and the webpage works well the route is being loaded everything is the same.

Thank you in advance

**Comment by andresz1** [comment]
Could this be related with this [issue](https://github.com/paulirish/pwmetrics/issues/211) ?

**Comment by denar90** [comment]
@carlesnunez what version of Lighthouse did you use?

**Comment by denar90** [comment]
I've published a new version included the latest Lighthouse, believe it should be fixed. Feel free to reopen it in case of a problem is still present.
