### ISSUE TITLE
No actual value of each bar in the graph is painted

### ISSUE THREAD

**Issue by rpkoller** [paulirish/pwmetrics#22]
Hi I ran into an possible issue. I am running `node 7.4.0` installed with homebrew on osx. I've installed `lighthouse@1.4.1` and `pwmetrics@1.2.3` globally with `npm install -g`. When i run either `pwmetrics` or with the `—runs=3` option I get an output like this. 

![bildschirmfoto 2017-01-10 um 11 43 42](https://cloud.githubusercontent.com/assets/1665422/21803367/168cb2c0-d72a-11e6-9d77-01c3bd7b0d62.png)

I get an rough idea about the dimension by the 10.000 value on the x-axis but the specific values are missing like in the example screenshot in the `readme.md` file. If you need any further informations let me know. Best regards r.

**Comment by denar90** [comment]
@rpkoller thanks for pointing this out. We have fix for it.
