### ISSUE TITLE
Timings are undefined when multiple runs are performed.

### ISSUE THREAD

**Issue by motss** [paulirish/pwmetrics#24]
Just get it installed on macOS Sierra with NPM on Node.js 7.4.0: `npm install -g pwmetrics`.

Performed multiple runs (`pwmetrics http://example.com/ --runs=3`) on any website and get the following error:
````
TypeError: Cannot read property 'timings' of undefined
    at results.map.r (/usr/local/lib/node_modules/pwmetrics/lib/index.js:127:41)
    at Array.map (native)
    at PWMetrics.findMedianRun (/usr/local/lib/node_modules/pwmetrics/lib/index.js:127:31)
    at PWMetrics.allDone.then._ (/usr/local/lib/node_modules/pwmetrics/lib/index.js:40:27)
```

**Comment by denar90** [comment]
Hi @motss . Yeah, bug is present in current release. Try to install it like `npm i -g paulirish/pwmetrics`. It will use latest `master`.

In nearest release it will be fixed. 

Here's my results using master.
![pwmetrics-master-run-3](https://cloud.githubusercontent.com/assets/6231516/21844401/2b968eb6-d7f7-11e6-99c3-d79c210585fe.png)

Thanks.

**Comment by paulirish** [comment]
I've pushed 1.2.4 to npm which should resolve this.

thanks very much for reporting, @motss !
