### ISSUE TITLE
Thoughts/questions about throttling

### ISSUE THREAD

**Issue by denar90** [paulirish/pwmetrics#26]
I've been thinking, since on localhost we don't have any roundtrips or another delays which can extend time of resources loading, do we have to add some default, e.g. 3G throttling, for measuring?  

- It can make it more real, can't it?
- Can we use some devtools API for that? 
- Should it be done as part of `lighthouse`?

**Comment by paulirish** [comment]
lighthouse is already doing network throttling by default.
https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/lib/emulation.js#L44

so we should be seeing that.

lighthouse DOES support cpu throttling, although it's not enabled right now
i'm interested in turning on CPU throttling to 3.5x for all pwmetrics runs.  wanna try that out?

**Comment by denar90** [comment]
I'm eager to work on that.

**Comment by paulirish** [comment]
right now you should be able to pass `{ disableCpuThrottling: false }` through as a flag to Lighthouse then you'll get a 5x slowdown. Either right in our lhOpts or maybe lhOpts.flags... i don't have time to check right now. :)

**Comment by denar90** [comment]
Resolved by https://github.com/paulirish/pwmetrics/commit/10751d3c31d6bb61395585600913d58460096f98
