### ISSUE TITLE
TracingStartedInPage event not found.

### ISSUE THREAD

**Issue by hemanth** [paulirish/pwmetrics#3]
Just noticed:

```
$ pwmetrics https://jsfeatures.in
Event RendererMain.START_MSG_LOOP has already been started
Event RendererMain.START_MSG_LOOP has already been started
TracingStartedInPage event not found.
Sorry, Visually Complete 85% metric is unavailable
```

Looks like it's something to do with [user-timings](https://github.com/GoogleChrome/lighthouse/blob/c87fab5f1fb2aa0daba1c949c564dc62b61c9faa/lighthouse-core/audits/user-timings.js#L64)

**Comment by paulirish** [comment]
Filed https://github.com/GoogleChrome/lighthouse/issues/617 upstream to tackle part of this.

Interesting that you get the start_msg_loop log, but that's a bug on the devtools side we need to sort out.  
Did you have any results at all on this run?

**Comment by hemanth** [comment]
```
$ pwmetrics --json https://jsfeatures.in
{
  "timings": [
    {
      "name": "First Contentful Paint",
      "value": 1875.337
    },
    {
      "name": "First Meaningful Paint",
      "value": 1970.7
    },
    {
      "name": "Median Visual Completion",
      "value": 1997
    },
    {
      "name": "First Visual Change",
      "value": 1917
    },
    {
      "name": "Visually Complete 100%",
      "value": 2004
    },
    {
      "name": "Time to Interactive",
      "value": -1
    },
    {
      "name": "Visually Complete 85%"
    },
    {
      "name": "Navigation Start",
      "value": 0
    }
  ],
  "timestamps": [
    303915241.28
  ]
}
```

![image](https://cloud.githubusercontent.com/assets/18315/18071921/1976eb8e-6e77-11e6-8d8c-7893971fd5af.png)


From [nmow](https://nmotw.in/pwmetrics/) ;)

**Comment by paulirish** [comment]
probably addressed now.
