### ISSUE TITLE
Feature request: ability to display chart AND metrics errors/warnings

### ISSUE THREAD

**Issue by MickeyKay** [paulirish/pwmetrics#32]
First off, fantastic project - I love it! Thanks a ton for working on this, and in general for all the great FE work you do.

Secondly, I have a feature request. At present, pwmetrics allows you to either 1. display a performance chart or 2. include expectation metrics and display errors/warnings, however you can't do both: https://github.com/paulirish/pwmetrics/blob/master/lib/index.js#L75. According to the logic here, a chart will only ever be output if no expectations are set.

My request is to add the ability to display the chart and any expectation errors/warnings.

**Comment by denar90** [comment]
#33 merged
