### ISSUE TITLE
Store json results into the file

### ISSUE THREAD

**Issue by denar90** [paulirish/pwmetrics#34]
Right now we are showing json result directly in console. It will be nice to save them into the file too.
Kinda `pwmetrics http://example.com --json=./pwmetrics-results.json`

**Comment by paulirish** [comment]
how about `pwmetrics http://example.com --json > pwmetrics-results.json` ?

**Comment by denar90** [comment]
SGTM, maybe it's time to use some lib like `yargs` ?

**Comment by paulirish** [comment]
@denar90 yup i'm supportive of adopting yargs to handle all that CLI stuff.. wanna take a go at it?

**Comment by denar90** [comment]
Of course, would love to 😃

**Comment by pedro93** [comment]
@denar90 would you like some help to add yargs to the project?

**Comment by denar90** [comment]
@pedro93 I've done some work on this. So you can create PR if there smth to improve.
Thanks :)
