### ISSUE TITLE
Measure bunch of pages

### ISSUE THREAD

**Issue by denar90** [paulirish/pwmetrics#35]
I think it can be useful to have possibility measure bunch of pages with running one command.
Right now we should do 

```
pwmetrics http://example.com --runs=3
pwmetrics http://example.com/page1 --runs=3
pwmetrics http://example.com/page2 --runs=3
```

I think we should do smth either like
`pwmetrics http://example.com http://example.com/page2 --runs=3`

or use some config property
```js
module.exports = {
  urls: ['http://example.com', 'http://example.com/page1'. 'http://example.com/page2']
}
```

**Comment by paulirish** [comment]
i guess it depends on the usecase. 

if you want to measure a BUNCH then you probably want to save the results as JSON or submit all to sheets?

dunno if you'd want to do a bunch of diff URLs and view the charts in the CLI.

**Comment by denar90** [comment]
Yeap, it's really just for `json` or `sheets` cases. We should postpone this a bit...

I'm just creating issues when smth pops out... 💡

**Comment by denar90** [comment]
Lets close it.
