### ISSUE TITLE
Metrics are not normalized

### ISSUE THREAD

**Issue by MickeyKay** [paulirish/pwmetrics#36]
Metrics are normalized when running pwmetrics through CLI, however they are not when pwmetrics is required as a module. The `get_config()` method in `expectations.js` makes the following two calls:
```
validateMetrics(expectations.metrics);
normalizeMetrics(expectations.metrics);
```

This turns metrics like `>=500` (this is what is documented in the readme, both for `package.json` as well as directly passing options to the constructor), into basic integers by stripping the `>=`.

These methods are not applied, however, when invoking pwmetrics as an included module. I assume this is an unintentional omission, as it prevents fully consistent behavior between CLI/package.json and module opt configurations.

The easy fix is adding the above-listed validation and normalization methods to the `PWMetrics` constructor.

**Comment by denar90** [comment]
It has to be fixed before releasing sheets stuff.

**Comment by denar90** [comment]
#37 merged
