### ISSUE TITLE
Add eslint

### ISSUE THREAD

**Issue by denar90** [paulirish/pwmetrics#43]

**Comment by pedro93** [comment]
I'm 100% in favor of this. @paulirish @denar90 do either of you have any specific eslint rule files you want to use or shall we use [lighthouse's one](https://github.com/GoogleChrome/lighthouse/blob/master/.eslintrc.js) ?

**Comment by paulirish** [comment]
Id be happy to use lighthouses rules

**Comment by pedro93** [comment]
Since we added and merged eslint rules in https://github.com/paulirish/pwmetrics/pull/73 im closing this, feel free to reopen.
