### ISSUE TITLE
Median Run output inconsistent with normal output

### ISSUE THREAD

**Issue by pedro93** [paulirish/pwmetrics#44]
This is a minor issue but might create some confusion for some users.
When running pwametrics with the ```runs``` flag the final median output's labels and data are not in the same order as the rest:

![screen shot 2017-01-30 at 15 00 28](https://cloud.githubusercontent.com/assets/3718654/22427891/da911a08-e6fc-11e6-9738-89f7f60c5097.png)

Notice how the last graph's labels are:
 - Time to Interactive
 - Perceptual Speed Index
 - First Meaningful Paint
 - First Contentful Paint

And the run graphs (which match the standard ```$ pwmetrics {url}``` output):
 - First Contentful Paint
 - First Meaningful Paint
 - Perceptual Speed Index
 - Time to Interactive

Merely changing this [line](https://github.com/paulirish/pwmetrics/blob/master/lib/index.js#L105) to:
```js
let timings = data.timings;
```

(Basically remove the ```.reverse()```)
Appears to fix the issue.

**Comment by denar90** [comment]
@pedro93 thanks, nice catch 👍  Do you wanna make a PR?

**Comment by pedro93** [comment]
Its a very minor change, I can if you want :)

**Comment by denar90** [comment]
Merged #46
