### ISSUE TITLE
Median values not precise

### ISSUE THREAD

**Issue by pedro93** [paulirish/pwmetrics#45]
This may be due to JS's math quirks with doubles and I might just be me nitpicking (if it is I apologize and do close the issue) but I ran pwmetrics on a webpage with 5 runs of which the outputted Time to Interactive metrics were:
 - 2,038
 - 2,026
 - 2,037
 - 2,043
 - 2,037

And a median Time to Interactive of: 2,037

With very simple math: 
2,038 + 2,026 + 2,037 + 2,043 + 2,037 = 10,181
10,181 / 5 = 2,0362

The other metrics were similarly slightly off. 
I know a possibility may be numbers rounding that are done only at the final stage but the user has no such indication.

If this is not a bug could there be an output message (or modify the ```Time (ms) since navigation start```) which states values may be incorrect by a given interval (+- 10ms)?

**Comment by paulirish** [comment]
you're calculating an average. i've selected the median. two different things. :)

**Comment by pedro93** [comment]
You're right! Thanks for explaining :)
I'll close this.
