### ISSUE TITLE
Reduce output when doing runs

### ISSUE THREAD

**Issue by pedro93** [paulirish/pwmetrics#47]
Consider only outputting the median graph data after all runs conclude.
Reason: Less information outputted to console and less cognitive load for the user. 

Personally if I ask pwmetrics to execute a number of times I'm more interested in seeing the median values than any 1 execution. 

Instead of displaying the chart of every run, pwmetrics could generate a file (JSON, CSV, whatever) with the data of every run but output to the console the chart for the median values. I understand there is a "sheets" configuration option but that requires configuring a google sheets and time to setup up. I propose a more "local" approach.

I could make a PR for this if the maintainers of this repository find it worthwhile to have this feature. To simply reduce the terminal output, the changes would occur here:
https://github.com/paulirish/pwmetrics/blob/master/lib/index.js#L84
By simply changing the if statement to:
```js  
if (!this.flags.submit && this.runs <= 1) {
    this.displayOutput(data);
}
```

Thoughts? @denar90 @paulirish

**Comment by paulirish** [comment]
Yup i support doing something different here.

Minimal visual output seems good to me.

**Comment by pedro93** [comment]
Do you have any suggestions? I can make a PR that would save a json or csv with the intermediate runs.

**Comment by denar90** [comment]
We have related issue here https://github.com/paulirish/pwmetrics/issues/34
I'm ok for now just reducing number of graphics which will be shown.

**Comment by denar90** [comment]
Looks like solved.
