### ISSUE TITLE
Config file not working

### ISSUE THREAD

**Issue by pedro93** [paulirish/pwmetrics#48]
I am trying to create a configuration file to use with pwmetrics however it is not being used by the library. I have a file performance-test.config.js that looks like this:
```js
module.exports = {
    runs: 5,
    flags: {
        expectations: true,
    },
    sheets: {
        // sheets configuration
    },
    expectations: {
        ttfmp: {
            warn: '>=3000',
            error: '>=5000',
        },
        tti: {
            warn: '>=5000',
            error: '>=15000',
        },
        ttfcp: {
            warn: '>=1500',
            error: '>=3000',
        },
        psi: {
            warn: '>=3000',
            error: '>=6000',
        },
    },
};
```

I'm executing pwmetrics like this:
```js
function runPerf(url, cb){
    const pwmetrics = path.join(__dirname, '../node_modules/pwmetrics/bin/cli.js');
    const perfConfig = require('../config/performance-test.config.js');
    const child = cp.exec('node ' + pwmetrics + ' ' + url + ' --config=' + perfConfig);
    child.stderr.pipe(process.stderr);
    child.stdout.pipe(process.stdout);
    child.on('close', (code) => {
        cb(code);
    });
}
```

I think the issue is with how the [cli](https://github.com/paulirish/pwmetrics/blob/master/bin/cli.js) reads the options from the command line. Is there an option to override every command line option with the data from a json?

**Comment by denar90** [comment]
Do you use latest version (1.2.4) or master? API you wanna use is in master branch and it hasn't been release yet.

---
Tips:
 - use `npm i paulirish/pwmetrics --save-dev` (until we release new awesome stuff)
 - use API for modules described in doc - https://github.com/paulirish/pwmetrics#api instead of executing cli.

E.g.
`my_module.js`
```js
const PWmetrics = require('pwmetrics');
const perfConfig = require('path-to-my-config/config.js');
....
function runPerf(url, cb){
  const pwmetrics = new PWmetrics(url, pwmetricsConfig);
  pwmetrics.start().then(cd);
}
```

`perfConfig.js`
```js
module.exports = {
    //flags - the place where cli options can be put
    flags: {
        expectations: true,
        runs: 5
    },
    sheets: {
        // sheets configuration
    },
    expectations: {
        ttfmp: {
            warn: '>=3000',
            error: '>=5000',
        },
        tti: {
            warn: '>=5000',
            error: '>=15000',
        },
        ttfcp: {
            warn: '>=1500',
            error: '>=3000',
        },
        psi: {
            warn: '>=3000',
            error: '>=6000',
        },
    },
};
```

**Comment by pedro93** [comment]
Thank you for the reply!

I will try it out tomorrow and report back but my use case requires that I use the cli version because I want to create a child process for running pwmetrics (in essence I want to deploy an express server and run pwmetrics on it, all in one go). 

If this is not possible with the cli, I'll try the library and create an external script which I'll call from my cp.exec call though I don't find that a good solution either...

Appreciate the help @denar90 :)

**Comment by denar90** [comment]
@pedro93 feel free to reopen it.
