### ISSUE TITLE
Share results with timeline viewer

### ISSUE THREAD

**Issue by denar90** [paulirish/pwmetrics#49]
Thought:
1. Submit results from lighthouse into gist/gdrive/whatever
2. Share it with [timeline viewer](https://github.com/ChromeDevTools/timeline-viewer)

I dunno if it has to be a part of `pwmetrics`, maybe `lighthouse` 

@paulirish thoughts?

**Comment by paulirish** [comment]
Yup love this general idea. :)

Timelines are like 5-100mb so i dont think gist will work. but gdrive should be fine.

**Comment by denar90** [comment]
👍 
I hope we can reuse outh stuff which we already have :)

**Comment by pedro93** [comment]
Question, how would this feature work for multiple runs?

**Comment by denar90** [comment]
Just store data to gdrive and open timeline viewer for each run.
