### ISSUE TITLE
Add some of features from pwmetrics-helper

### ISSUE THREAD

**Issue by denar90** [paulirish/pwmetrics#52]
Right now `pwmetrics` can do more then [pwmetrics-helper](https://github.com/addyosmani/pwmetrics-helper), to have one place to manage progressive web metrics I propose to add some missed features  (get `desiredMetric `) which `pwmetrics-helper` has and propose @addyosmani to deprecate it.

**Comment by pedro93** [comment]
I agree especially after https://github.com/paulirish/pwmetrics/pull/51 merges.

**Comment by denar90** [comment]
So we should just add `desiredMetric` feature.
Should we draw chart?
Should we check expectations if `expectations` flag and `desiredMetric` are set? (personally 👍)

**Comment by pedro93** [comment]
Just to bring this alive, should we merely add the code from that repo or re-create the functionality in a more integrated manner?  @denar90 @paulirish depending on how strongly you feel, it would require a large code re-write.

**Comment by denar90** [comment]
The code which can be reused is just one function :)
https://github.com/addyosmani/pwmetrics-helper/blob/master/index.js#L30-L32

You can easy copy/paste it, add cli flags and stuff.

**Comment by pedro93** [comment]
Does it make sense to have a cli flag for this? if so, how should it look? This functionality is is more of an API addition.

**Comment by denar90** [comment]
I think `desiredMetric` will be fine. It should be possible to use through cli and API.

**Comment by pedro93** [comment]
Should desiredMetric be applied to the median run or all runs, should you only specify one or can you provide a list to run? Also we can do an improvement here that is to tell lighthouse to run the specified audits. As of right now and https://github.com/addyosmani/pwmetrics-helper does this, is to run lighthouse as is right now (with perf audits) and filter the results for only the desired metric (only 1).
