### ISSUE TITLE
Remove duplicated pwmetrics object properties and merging yargs support

### ISSUE THREAD

**Issue by pedro93** [paulirish/pwmetrics#53]
Whilst reading through the project I noticed the [pwmetrics object](https://github.com/paulirish/pwmetrics/blob/master/lib/index.js#L22) contains a property ```opts``` which is not used anywhere else, and will in fact duplicate the object size in memory. 

If you agree @paulirish I would like to do a code cleanup for this and some other minor fixes across files including adding the [yargs PR](https://github.com/paulirish/pwmetrics/pull/51), improve upon it and potencially add support for https://github.com/paulirish/pwmetrics/issues/48.

Should this all be done as a pull request for you to later review?
@denar90 do you agree with this?

**Comment by denar90** [comment]
SGTM
just one question about #48 
What exactly do you wanna improve? Passing `flags` from confg file?

**Comment by pedro93** [comment]
I was thinking of populating the pwmetrics object with the properties from the config file in case one exists. If there are repeated parameters both in a config file and from the cmd line, then the cmd line should take precedent.
Imagine something like:

performance.config.js
```js
module.exports = {
    url: "http://github.com",
    json: false,
    runs: 5,
    flags: {
        expectations: true,
    },
    sheets: {
        // sheets configuration
    },
    expectations: {
        ttfmp: {
            warn: '>=3000',
            error: '>=5000',
        },
        tti: {
            warn: '>=5000',
            error: '>=15000',
        },
        ttfcp: {
            warn: '>=1500',
            error: '>=3000',
        },
        psi: {
            warn: '>=3000',
            error: '>=6000',
        },
    },
};
```

Bash
```
$ pwmetrics --config="path/to/file.js" --json
```

The json option in the terminal overrides the config option. A use case for this would be wanting to see results with slightly different options but no having to change the actual file (which you may not have permissions to edit). This would also potentially allow any configuration to be set via the command line that can also be set in the config file.

This logic should be done IMO in the bin/cli.js file after yargs has been merged, hence the dependency.

**Comment by denar90** [comment]
Oh, got your point. Make sense. 
Lets do it 💪  I'm ok to make it in scope of yargs PR. Jut make PR against `yargs` branch, so I'll merge it together.

**Comment by pedro93** [comment]
@paulirish do you approve? If so I will start working on this. I do have a question though, what is the rationale behind this loop?
https://github.com/paulirish/pwmetrics/blob/master/bin/cli.js#L24

**Comment by denar90** [comment]
It's redundant from old API. Going with your suggestion we can do smth like
`config.flags = Object.assign({}, flagsFromFile, cliFlags)`

**Comment by paulirish** [comment]
I suppose this is done, now that we have our combined refactor in place? :)

Pedro, feel free to reopen if we got more here!
