### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by denar90** [paulirish/pwmetrics#55]
- [x] TypeScript usage. Will help us to reduce number of tests and make lib more reliable. 
 - [x] Yargs - https://github.com/paulirish/pwmetrics/pull/51
 - [x] metricsDefinitions - https://github.com/paulirish/pwmetrics/pull/50 (after Lighthouse release)
 - [x] Handle CRI_TIMEOUT error - https://github.com/paulirish/pwmetrics/pull/42
 - [x] test sheets functionality - https://github.com/paulirish/pwmetrics/pull/38
 - [x] refactor/tests for [expectations](https://github.com/paulirish/pwmetrics/blob/master/lib/expectations.js) like it was done for sheets  https://github.com/paulirish/pwmetrics/pull/38
 - [x] tests for [recordLighthouseTrace](https://github.com/paulirish/pwmetrics/blob/master/lib/index.js#L79) postponed
 - [x] tests for [appendResults](https://github.com/paulirish/pwmetrics/blob/master/lib/index.js#L147) postponed
 - [x] tests for [findMedianRun](https://github.com/paulirish/pwmetrics/blob/master/lib/index.js#L175)
 - [x] refactor/tests for [gsheets](https://github.com/paulirish/pwmetrics/blob/master/lib/gsheets/gsheets.js) like it was done for sheets  https://github.com/paulirish/pwmetrics/pull/38
- [x] https://github.com/paulirish/pwmetrics/issues/53, https://github.com/paulirish/pwmetrics/issues/48 (postponed)
- [x] https://github.com/paulirish/pwmetrics/issues/28, https://github.com/paulirish/pwmetrics/issues/31 kinda critical, but depends on lighthouse fix https://github.com/GoogleChrome/lighthouse/pull/1672

Anything to add, thoughts

**Comment by pedro93** [comment]
Yargs related tests.
Configuration file parameter validation.

There are also inconsistencies in the README about how to use the config file and certain flags uses. @denar90 if you would like I can talk to you over slack or something and explain.

**Comment by denar90** [comment]
updated priority

**Comment by pedro93** [comment]
We have promise chains without catch blocks which leads to hidden error messages. These should be cleaned up for a better error processing and logging.

E.g: If we catch an error [here](https://github.com/paulirish/pwmetrics/blob/master/lib/index.js#L133), we will not have access to a correct stack trace: 

![screen shot 2017-02-27 at 13 04 36](https://cloud.githubusercontent.com/assets/3718654/23362356/5062bab0-fced-11e6-85c8-3f077cbc9537.png)

**Comment by denar90** [comment]
So, the status.
We are about to finish stuff for v2 🎉 

In a next few days I'll work on docs, improving it and test all stuff. @pedro93 wanna help me in testing?

----

@paulirish @samccone @pedro93 I prepared some draft [article](https://medium.com/@denar90/easy-progressive-web-metrics-9afa5ed857c2) about `pwmetrics` and it's features, which might help people use it. I'd be glad to hear your thoughts about it. Thx :)

**Comment by pedro93** [comment]
Sure @denar90, just need a quick rundown of the use cases and i'll start to have a look.

**Comment by denar90** [comment]
@paulirish let's roll this out 🚀 

p.s. will be good to add some topics for repo) nice extensions for chrome - https://github.com/yavorsky/auto-github-topics

**Comment by pedro93** [comment]
Let's do it! :+1:

**Comment by paulirish** [comment]
because of @samccone's very nice [tweet](https://twitter.com/samccone/status/854712077436436480) i hustled out a 1.3.1 release that's effectively our 2.0.

it includes a bump to lighthouse and various fixes for that. check https://github.com/paulirish/pwmetrics/commits/master to see them.
afaik it wont have the missing typescript file problems that we have with installing from github. 

apologies for shipping "2.0" a tad early, but just wanted to shortcircuit issues like #99.

**Comment by paulirish** [comment]
@denar90 btw i'm happy to rebump this release as 2.0. i just was doing the fast thing to handle today's traffic. :)

also remind me to tweet out your article!

**Comment by denar90** [comment]
Yeap, Sam made us react quickly :) 
Paul, can you wait about 30 min, I'll manually recheck PR -
 https://github.com/paulirish/pwmetrics/pull/102 so maybe we can land this fix too.
P.S. I've published article about our possibilities https://twitter.com/denar90_/status/854797794829316097

**Comment by paulirish** [comment]
i just published 1.3.2 which contains the terminal fix along with invalidprotoexpectation fix.

**Comment by denar90** [comment]
🎉  Just woke up and found out that so many stuff is going around. 
Do you wanna either release v2 or we will stick to `1.3.x` instead?

**Comment by paulirish** [comment]
i think we should retag as 2.0. i'd love you to take the honors of that. :)

**Comment by denar90** [comment]
@paulirish thank you for letting me do that!
v2 is landed 🚀 
Thanks to all of you guys @paulirish @samccone @pedro93 
Cheers 🍺 💃 

P.S. If someone is interested in v2 features, we have some article for you https://medium.com/@denar90/easy-progressive-web-metrics-9afa5ed857c2

**Comment by pedro93** [comment]
AMAZING! 🤗🤗🤗🤗
