### ISSUE TITLE
CI issue after updating lighthouse version

### ISSUE THREAD

**Issue by denar90** [paulirish/pwmetrics#63]
We have issue on CI after finishing measurements.
https://travis-ci.org/paulirish/pwmetrics/jobs/204950872#L722-L735

So I found that it's related to killing launched chrome.
Everything is fine if we don't kill it.

Here is my commit with changes.
I've removed all logic related to charts and stuff.

Diff - https://github.com/paulirish/pwmetrics/compare/master...denar90:dont-kill-chrome
CI - https://travis-ci.org/denar90/pwmetrics/jobs/205395193

Then I downgraded version to `1.4.1` and it works perfectly

Diff - https://github.com/paulirish/pwmetrics/compare/master...denar90:test-ci-with-1.4.1
CI - https://travis-ci.org/denar90/pwmetrics/jobs/205392241

I suppose that something has changed in chrome launcher in `1.5.x`...

cc @paulirish @samccone

**Comment by paulirish** [comment]
FWIW this looks like the changes in chromelauncher between 1.4.1 and 1.5.1:

![image](https://cloud.githubusercontent.com/assets/39191/23336690/a2abd4ae-fb8b-11e6-8abb-ebf45160e4ac.png)

nothing looks particularly relevant. there was some protection added so lighthouse doesnt launch multiple chrome processes.

lighthouse also throws more errors during runtime for various reasons, but this seems to be happening after all that. so yeah. i'm confused as well. :)

**Comment by denar90** [comment]
Yeap nothing what could break stuff...
So, it's problem somewhere in our code...
I thought maybe smth wrong with travis setup but no...
Pure lighthouse works fine
https://github.com/paulirish/pwmetrics/compare/master...denar90:try-lighthouse-with-ci
https://travis-ci.org/denar90/pwmetrics/jobs/205463498

Will dig into this stuff. Maybe we run chrome with wrong params, but no, maybe something else...

**Comment by denar90** [comment]
I finally caught the bug.
This issue is related to delay between starting and stoping chrome process.
If we have good delay (e.g. 1000 ms) then it works fine.
in lighthouse (lighthouse http://example.com) itself we have really big one (because of all calculations and output stuff) that's why bug doesn't appear on CI, I think.

---

So here we are.

I've added timeout after lighthouse done it's work
And CI is fixed :tada:

**Commit with timeout**
Diff commit - https://github.com/paulirish/pwmetrics/compare/master...denar90:f5b36f0df3813257395c9cf6c077621df2a37dda#diff-0d0c1d3a66e2f517426ba230670cbaacR46
CI - https://travis-ci.org/denar90/pwmetrics/jobs/205728447#L621-L623

**Commit without timeout**
Diff commit - https://github.com/paulirish/pwmetrics/compare/master...denar90:26ace0c2822c10e5eb646dd4287e29bb9dc05817#diff-0d0c1d3a66e2f517426ba230670cbaacR43
CI - https://travis-ci.org/denar90/pwmetrics/jobs/205732286#L621-L634

--- 

I've measured time between versions without timeouts and stuff and got confused... :disappointed: 

Here some measurements with 1.4.1 and 1.5.1 lighthouse versions.

|         |        node 6       |        node 7        |
|:-------:|:-------------------:|:--------------------:|
| v1.4.1 | 5 sec 418.057435 ms |   3 sec 16.127497 ms |
| v1.5.1 | 4 sec 433.328276 ms |  4 sec 493.901057 ms |

Diff for v.1.4.1 test https://github.com/paulirish/pwmetrics/compare/master...denar90:e21dca6ec5321c9d0eca8d734c29432266d98535#diff-6d186b954a58d5bb740f73d84fe39073

Travis - https://travis-ci.org/denar90/pwmetrics/builds/205764350

Diff for v1.5.1 test https://github.com/paulirish/pwmetrics/compare/master...denar90:0fcfb92d651e66169e7534d36f60e4abe7530766#diff-6d186b954a58d5bb740f73d84fe39073

Travis - https://travis-ci.org/denar90/pwmetrics/builds/205765280

So, I'm really confused why it's happening, because there are no too much delay time between versions...

cc @paulirish @samccone

**Comment by pedro93** [comment]
Any update on this? @paulirish @samccone

**Comment by pedro93** [comment]
@denar90 can we close this issue or is there anything else we can do?

**Comment by denar90** [comment]
It's an important one because we can't run `pwmetrics` on CI, so other people might face same issue...
