### ISSUE TITLE
Cleaner error messaging when using invalid parameters

### ISSUE THREAD

**Issue by pedro93** [paulirish/pwmetrics#65]
Just a note, when running the cli tool with invalid parameters a cleaner output should be shown:

![screen shot 2017-02-27 at 12 29 14](https://cloud.githubusercontent.com/assets/3718654/23361432/8c4849dc-fce8-11e6-867d-0b91ccebf4ca.png)

This happens because we have no try catch block to handle this exception. We can fix this by doing the following In the [cli.js file test section](https://github.com/paulirish/pwmetrics/blob/master/bin/cli.js#L68)
```js
if (!options.url || !options.url.length) {
   console.err(getMessage('NO_URL'));
   process.exit(-1);
}
```

Also I would prefer the Error message outputed from getMessageWithPrefix, its a little more visual for the user.

**Comment by denar90** [comment]
solved by #67
