### ISSUE TITLE
Cannot read property 'ts' of undefined Audit key: first-meaningful-paint.

### ISSUE THREAD

**Issue by pedro93** [paulirish/pwmetrics#74]
Not sure if this is an upstream bug, i can not consistently reproduce it.

![screen shot 2017-03-13 at 11 13 52](https://cloud.githubusercontent.com/assets/3718654/23852128/4270b8a2-07de-11e7-8ebb-1d3a60380191.png)

Any thoughts as to what this might be?

**Comment by denar90** [comment]
It's related to https://github.com/GoogleChrome/lighthouse/issues/1253
closing though
