### ISSUE TITLE
couldn't find pc offset for node=119

### ISSUE THREAD

**Issue by pedro93** [paulirish/pwmetrics#75]
Possible upstream bug, first time occurence. Can not reproduce.

<img width="1269" alt="screen shot 2017-03-15 at 14 58 18" src="https://cloud.githubusercontent.com/assets/3718654/23954702/ea8fbbfc-098f-11e7-858c-88ef67332d19.png">

**Comment by denar90** [comment]
@pedro93 closing, feel free to reopen.
