### ISSUE TITLE
Change CI yarn installation method

### ISSUE THREAD

**Issue by pedro93** [paulirish/pwmetrics#82]
Due to recent changes in one of yarn's npm dependencies, the our CI build broke temporarily, see https://github.com/yarnpkg/yarn/issues/2915. 
To prevent this in the future I would suggest we remove the yarn dependency in the project's package.json and modify our [.travis.yml file before install step](https://github.com/paulirish/pwmetrics/blob/master/.travis.yml#L17) to the suggested [linux installation method](https://yarnpkg.com/en/docs/install#linux-tab). 

Thoughts @denar90 ?

__EDIT__: Just noticed PR https://github.com/paulirish/pwmetrics/pull/79 could this change be made there to guarantee yarn stability?

**Comment by denar90** [comment]
I dunno, but using yarn `0.22.0` help - https://github.com/paulirish/pwmetrics/pull/79/files#diff-354f30a63fb0907d4ad57269548329e3R17

**Comment by pedro93** [comment]
I noticed, I wonder if it wouldn't be better to use the recommended yarn install method via Linux repositories and bash commands.

**Comment by pedro93** [comment]
Closing this as https://github.com/paulirish/pwmetrics/pull/79 has been merged. If yarn related installation problems occur again lets refer back to the https://github.com/paulirish/pwmetrics/issues/82#issue-216967014 solution
