### ISSUE TITLE
Error: No Chrome Installations Found

### ISSUE THREAD

**Issue by franklinjavier** [paulirish/pwmetrics#9]
Hi Paul, i'm facing some issue in initialization.
I have Chrome and Lighthouse installed

``` sh
franklin in ~ λ pwmetrics https://www.belezanaweb.com.br
Launching Chrome...
created /var/folders/vy/zs7j58x177781vgtdpdct0840000gn/T/lighthouse.XXXXXXX.96kRSm4v
[Error: No Chrome Installations Found]
```

**Comment by franklinjavier** [comment]
Related https://github.com/GoogleChrome/lighthouse/issues/689

**Comment by franklinjavier** [comment]
The solution was install the Chrome Canary

**Comment by paulirish** [comment]
K. Latest version of lighthouse should fix this

**Comment by franklinjavier** [comment]
🍻

**Comment by samccone** [comment]
this will also make this situation a lot better :) https://github.com/GoogleChrome/lighthouse/pull/898
