### ISSUE TITLE
Safeguard against 0 non-error run

### ISSUE THREAD

**Issue by pedro93** [paulirish/pwmetrics#93]
Make sure there is atleast 1 valid run when calling medianRun, see image below. I'll make a quick pull request for this.

![screen shot 2017-04-10 at 10 17 22](https://cloud.githubusercontent.com/assets/3718654/24854608/ffbc5566-1dd6-11e7-9250-803a13bb882f.png)

**Comment by denar90** [comment]
Solved by #94
